### ISSUE TITLE
Failed to load node_modules/pdf417-generator/lib/bcmath.js

### ISSUE THREAD

**Issue by jboarman** [pkoretic/pdf417-generator#10]
I can see the the file locally, so it doesn't make sense to me that it's complaining about not see this file in the path listed:  `node_modules/pdf417-generator/lib/bcmath.js`.

Can you confirm that this _should_ work?

I'm not sure why these dependencies are not being recognized since they are part of the NPM package itself.  I wouldn't think I would need to use CDN references if I have the NPM package installed.  Further, the build tool seems to think it should be accessible as well.  It might just be how I have the build script set up, but I would like to make sure that my expectations are right.

```bash
λ npm run build                                                               
                                                                              
> scanner-test@1.0.0 build                                                    
> snowpack build                                                              
                                                                              
[snowpack] ! building source files...                                         
[snowpack] ✔ build complete [0.24s]                                           
[snowpack] ! building dependencies...                                         
[snowpack] Failed to load node_modules/pdf417-generator/lib/bcmath.js         
  Unexpected token                                                            
[snowpack] Install failed.                                                    
```

**Comment by pkoretic** [comment]
Hi @jboarman 
not sure really what is the usecase with snowpack. 
npm install is not intended to be used for web frontend, that should just package .js files as usual.
