### ISSUE TITLE
How can I download the latest version 1.0.3 for bc-multiply resolution

### ISSUE THREAD

**Issue by jumanahalasadi** [pkoretic/pdf417-generator#11]
Hi, I need the fix here, https://github.com/pkoretic/pdf417-generator/issues/5 

When I do npm install pdf417-generator@latest i get version 1.0.2

Our project is using 
    "pdf417-generator": "^1.0.2",

And we are facing the bc-multiply error for special chars such as Chloè

Thanks!

**Comment by pkoretic** [comment]
Hi @jumanahalasadi 
indeed seems I forgot to publish it on npm, sorry for that, published now and thanks for reporting.

**Comment by jumanahalasadi** [comment]
Thanks for your quick response :)  @pkoretic
