### ISSUE TITLE
Issue with accents and special characters

### ISSUE THREAD

**Issue by jumanahalasadi** [pkoretic/pdf417-generator#13]
Hi there,

Our app is trying to encode the following delimited string in a barcode using the pdf417 generator and it contains a lot of accents for french words. The issue is that if there is an accent in between two repeated data items. 
The generator may potentially be adding extra fields / repeating data when we are decoding it. Please see below examples.

Can you please assist with troubleshooting the issue? We have narrowed it down to when any word with an accent is in the middle of two repeated fields.

**Original input string passed to the pdf 417 generator**

|anything|É|anything|

**Decoding the generated barcode:**

|anything||anything|É|anything|

This is breaking our app because the barcodes are giving wrong data / extra data when accents is present. 

Attaching the barcode generated 
<img width="492" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/14082336/117069746-ddec8980-acfa-11eb-8a19-8893e1bec32a.png">

Thank you in advance!

**Comment by jumanahalasadi** [comment]
@pkoretic  Hi Petar, just checking in. I hope you are doing well.

Can you please let us know if you have any thoughts about this. This is quite urgent for us. Thank you so much!

**Comment by monkeyDG** [comment]
Hi @pkoretic, hope all is well. Nudging this open issue again to see if you have any thoughts towards this. Cheers!

**Comment by daniellercole** [comment]
Hello @pkoretic! Any thoughts or updates on this issue? Hope to hear back from you. thank you!
