### ISSUE TITLE
The unescape() returns EspaÃ±a or GonzÃ¡lez instead of España or González

### ISSUE THREAD

**Issue by michaelandrewrm** [pkoretic/pdf417-generator#15]
https://github.com/pkoretic/pdf417-generator/blob/bf1894d202a3ec3c247a712cefe93b96b2aebab2/lib/pdf417.js#L436

**Comment by pkoretic** [comment]
Can you try the latest version? This shouldn't be valid actually anymore as UTF-8 is preferred.
