### ISSUE TITLE
Strict mode issue

### ISSUE THREAD

**Issue by pIvan** [pkoretic/pdf417-generator#3]
Hi @pkoretic,

library is great, but in our case when it is used with angular application
installed like npm package, and strict mode declared we have problem
with this two variables which are not declared.

sequence = this.getInputSequences(code);
codewords = []; // array of code-words

can you add var statement before them?

Thanks!

Kind regards,
Ivan

**Comment by pkoretic** [comment]
@pIvan thanks for bringing it up, should be good in master, will publish to npm as well.
