### ISSUE TITLE
Can I change barcode's size?

### ISSUE THREAD

**Issue by coltisor** [pkoretic/pdf417-generator#4]
I want the barcode bigger. Is there any way to setup it's size?

**Comment by coltisor** [comment]
I found a solution. You can call DRAW function with extra parameters.

Example:
`PDF417.draw(text, canvas, 2.666, 6, 3);`

As follows from library's code:
```
/**
	 * This is the class constructor.
	 * Creates a PDF417 object
	 * @param code (string) code to represent using PDF417
	 * @param aspectratio (float) the width to height of the symbol (excluding quiet zones)
	 * @param ecl (int) error correction level (0-8); default -1 = automatic correction level
	 * @param devicePixelRatio (int) determine how much extra pixel density should be added to allow for a sharper image
	 */
	draw: function(code, canvas, aspectratio, ecl, devicePixelRatio) {
...
}
```

**Comment by pkoretic** [comment]
Hi @hurryword, thanks for bringing it up, let me add it to readme.

**Comment by coltisor** [comment]
You're welcome. It doesn't really set the size :D It makes the barcode bigger, but the size varies. And I don't really know how to control it. For now I convert it to PNG, and then set max-width with CSS due to my needs. Text me if u know something I missed.
