### ISSUE TITLE
bc_multiply is not a function

### ISSUE THREAD

**Issue by pIvan** [pkoretic/pdf417-generator#5]
Hi @pkoretic in some cases we get an error
[bc_multiply](https://github.com/pkoretic/pdf417-generator/blob/eb8ae090746a40ee55187f2837414c8f49aa02a9/lib/bcmath.js#L201) is not a function.

stack trace:

> ERROR TypeError: r.bc_multiply is not a function
    at bcmul (main-es2015.a0fba3d24438133b4d38.js:1)
    at Object.getCompaction (main-es2015.a0fba3d24438133b4d38.js:1)
    at Object.draw (main-es2015.a0fba3d24438133b4d38.js:1)

Do you have any idea what would cause the problem?

Kind regards,
Ivan

**Comment by pkoretic** [comment]
Hi @pIvan 
this happens only sometimes? 
as far as I can see you are using some compiler/minifer, are you using dynamic minifier? can you try with regular include and see if this is happening?

Best regards,
Petar

**Comment by pIvan** [comment]
Hi @pkoretic,

I didn't try to use regular include, but also I can't find that method in [libbcmath](https://github.com/pkoretic/pdf417-generator/blob/eb8ae090746a40ee55187f2837414c8f49aa02a9/lib/libbcmath.js)

**Comment by ivangvozden** [comment]
I've encountered the same issue today. I've managed to reproduce it on the [live demo](https://pkoretic.github.io/pdf417-generator/) with minor changes to test data:

```
HRVHUB30
HRK
000000000012355
PETAR KORETIĆ
PREVOJ DD
10290 Zaprešić
QAAP J.D.O.O
PREVOJ DD
10290 Zaprešić
HR5041240000000000
HR01
7336-68949637625-00001
COST
Uplata za 1. mjesec
```

I had a similar use-case in which the address, city or name used for generating the barcode had more than one diacritic sign.

Stack trace in unminified script is:

```
Uncaught TypeError: libbcmath.bc_multiply is not a function
    at bcmul (bcmath.js:201)
    at Object.getCompaction (pdf417.js:755)
    at Object.draw (pdf417.js:447)
    at generate ((index):77)
    at HTMLTextAreaElement.oninput ((index):38)
```

**Comment by pkoretic** [comment]
Thank you @ivangvozden, especially for the reproducible case
Indeed the function is missing, let me fix that
