### ISSUE TITLE
Can I make it stand up by parameter?

### ISSUE THREAD

**Issue by zhnoah** [pkoretic/pdf417-generator#7]

**Comment by pkoretic** [comment]
Hi @zhnoah 
I'm not sure what you mean, change the qr drawing to be oriented differently?

**Comment by zhnoah** [comment]
like this

![image](https://user-images.githubusercontent.com/7981230/88635315-1c10a900-d0ea-11ea-938e-5d1e835f9890.png)

**Comment by pkoretic** [comment]
@zhnoah 
I believe you can just rotate a canvas element that is used for drawing
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/rotate
