### ISSUE TITLE
Blank when using Wkhtmltopdf

### ISSUE THREAD

**Issue by ghost** [pkoretic/pdf417-generator#9]
I think this is actually an issue with wkhtmltopdf, but I though you may have advice. The barcode renders fine in a normal browser, but when using wkhtmltopdf it's just blank. Any ideas?

**Comment by pkoretic** [comment]
Hi Jacquers.

I assume it's because the library is using canvas. Can you check if
wkhtmltopdf supports canvas elements or if there is something extra to
enable that?

**Comment by ghost** [comment]
I think Wkhtmltopdf has issues with canvas, It's not updated very frequently.  I've found a workaround by using another C# lib to generate the barcode and then using the result to have a basr64 encoded image.
